# Try out, compare, test lidar transformations
- Keeping it for transparency

In [ ]:
import numpy as np
import tensorflow as tf
import unittest

from lidar_compression.util.pointcloud_sort import add_spherical_coordinates, remove_distant_and_close_points, sort_points
from lidar_compression.util.pointcloud_sort_optimizations import sort_points_theta_phi_naive
from waymo_open_dataset.utils import  frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset

In [2]:
result = np.zeros((10,3))
for i in range(1,11):
    result[i-1] = np.array([i,i,i])
print(result)
print(np.percentile(result[:,0],78, interpolation='nearest'))

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.],
       [ 5.,  5.,  5.],
       [ 6.,  6.,  6.],
       [ 7.,  7.,  7.],
       [ 8.,  8.,  8.],
       [ 9.,  9.,  9.],
       [10., 10., 10.]])

In [4]:
points = np.zeros((10,3))
for i in range(1,11):
    points[i-1] = np.array([i,i,i])

correct_result = np.zeros((6,3))
for i in range(3,9):
    correct_result[i-3] = np.array([i,i,i])

reduced_points = remove_distant_and_close_points(points, min_percentile=22, max_percentile=78)
print(reduced_points)
print(correct_result)

[[3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]
[[3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]
 [7. 7. 7.]
 [8. 8. 8.]]


In [6]:
cartesian_points = np.array([[1,2,3], [-1,-2,-3], [5,6,3], [-5,3,10], [0,0,0], [10,10,10]], dtype=np.float)
cartesian_spherical_cloud = add_spherical_coordinates(cartesian_points)
sorted_cloud = sort_points(cartesian_spherical_cloud, 6,6)
sorted_cloud_naive = sort_points_theta_phi_naive(cartesian_spherical_cloud,6,6)

In [7]:
print(sorted_cloud)
print(sorted_cloud_naive)
print(np.array_equal(sorted_cloud, sorted_cloud_naive))

[[[ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 1.   2.   3. ]
  [ 0.   0.   0. ]
  [-5.   3.  10. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 7.5  8.   6.5]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [-1.  -2.  -3. ]]]
[[[ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 1.   2.   3. ]
  [ 0.   0.   0. ]
  [-5.   3.  10. ]
  [ 0.   0.   0. ]
  [ 0.   0.   0. ]]

 [[ 0.   0.   0. ]
  [ 7.5  8.   6.5]
  [ 0.   0.   0. ]
  [ 0.   0.   0

In [8]:
correct_result_xy = np.zeros((6,2))
correct_result_z = np.zeros((6,1))
for i in range(3,9):
    correct_result_xy[i-3] = np.array([i,i])
for i in range(9,2,-1):
    correct_result_z[8-i] = np.array([i])
correct_result = np.concatenate([correct_result_xy, correct_result_z], axis=1)
correct_result

array([[3., 3., 8.],
       [4., 4., 7.],
       [5., 5., 6.],
       [6., 6., 5.],
       [7., 7., 4.],
       [8., 8., 3.]])

In [9]:
result_xy = np.zeros((10,2))
result_z = np.zeros((10,1))
for i in range(1,11):
    result_xy[i-1] = np.array([i,i])
for i in range(10,0,-1):
    result_z[10-i] = np.array([i])
result = np.concatenate([result_xy, result_z], axis=1)
print(result)
print(result[2:8])
print(np.percentile(result, 100))

array([[ 1.,  1., 10.],
       [ 2.,  2.,  9.],
       [ 3.,  3.,  8.],
       [ 4.,  4.,  7.],
       [ 5.,  5.,  6.],
       [ 6.,  6.,  5.],
       [ 7.,  7.,  4.],
       [ 8.,  8.,  3.],
       [ 9.,  9.,  2.],
       [10., 10.,  1.]])