# Play around with our Lidar Transformation using Toy Examples
- Compare original data with our transformation
- Keeping it for transparency

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import lidar_compression.util.waymo_preprocessing as wp

from waymo_open_dataset.utils import  frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset

2021-08-16 18:09:05.335215: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


In [5]:
cartesian_points= np.array([[1,2,3], [-1,-2,-3], [5,6,3], [-5,3,10], [0,0,0], [10,10,10]], dtype=np.float)
cs = wp.add_spherical_coordinates(cartesian_points)
cs

array([[ 1.        ,  2.        ,  3.        ,  3.74165739,  0.64052231,
         1.10714872],
       [-1.        , -2.        , -3.        ,  3.74165739,  2.50107034,
         4.24874137],
       [ 5.        ,  6.        ,  3.        ,  8.36660027,  1.20406227,
         0.87605805],
       [-5.        ,  3.        , 10.        , 11.5758369 ,  0.52789675,
         2.60117315],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [10.        , 10.        , 10.        , 17.32050808,  0.95531662,
         0.78539816]])

In [6]:
r0_c0_values = np.array([cartesian_points[0][0:3], cartesian_points[2][0:3], cartesian_points[4][0:3],cartesian_points[5][0:3]])
r0_c1_values = np.array([cartesian_points[3]])
r1_c0_values = np.zeros((1,3))
r1_c1_values = np.array([cartesian_points[1]])

r0_c0 = np.array([r0_c0_values[:,0].mean(), r0_c0_values[:,1].mean(), r0_c0_values[:,2].mean()])
r0_c1 = np.array([r0_c1_values[:,0].mean(), r0_c1_values[:,1].mean(), r0_c1_values[:,2].mean()])
r1_c0 = np.array([r1_c0_values[:,0].mean(), r1_c0_values[:,1].mean(), r1_c0_values[:,2].mean()])
r1_c1 = np.array([r1_c1_values[:,0].mean(), r1_c1_values[:,1].mean(), r1_c1_values[:,2].mean()])
res = np.concatenate([r0_c0, r0_c1, r1_c0, r1_c1]).reshape((2,2,3))
print(r0_c0_values)
print(r0_c1_values)
print(r1_c0_values)
print(r1_c1_values)

print()
print("r0_c0: " + str(r0_c0))
print("r0_c1: " + str(r0_c1))
print("r1_c0: " + str(r1_c0))
print("r1_c1: " + str(r1_c1))

print()
print("res:")
print(res)
print("Shape:")
print(res.shape)

[[ 1.  2.  3.]
 [ 5.  6.  3.]
 [ 0.  0.  0.]
 [10. 10. 10.]]
[[-5.  3. 10.]]
[[0. 0. 0.]]
[[-1. -2. -3.]]

r0_c0: [4.  4.5 4. ]
r0_c1: [-5.  3. 10.]
r1_c0: [0. 0. 0.]
r1_c1: [-1. -2. -3.]

res:
[[[ 4.   4.5  4. ]
  [-5.   3.  10. ]]

 [[ 0.   0.   0. ]
  [-1.  -2.  -3. ]]]
Shape:
(2, 2, 3)


In [7]:
num_rows = 2
num_cols = 2
cartesian_points= np.array([[1,2,3], [-1,-2,-3], [5,6,3], [-5,3,10], [0,0,0], [10,10,10]], dtype=np.float)
cartesian_spherical_points = wp.add_spherical_coordinates(cartesian_points)
sorted_points = wp.sort_points_theta_phi(cartesian_spherical_points, num_cols=num_cols, num_rows=num_rows)

In [8]:
print(r0_c0_values)
print(r0_c1_values)
print(r1_c0_values)
print(r1_c1_values)

[[ 1.  2.  3.]
 [ 5.  6.  3.]
 [ 0.  0.  0.]
 [10. 10. 10.]]
[[-5.  3. 10.]]
[[0. 0. 0.]]
[[-1. -2. -3.]]


In [9]:
print(cartesian_spherical_points)

[[ 1.          2.          3.          3.74165739  0.64052231  1.10714872]
 [-1.         -2.         -3.          3.74165739  2.50107034  4.24874137]
 [ 5.          6.          3.          8.36660027  1.20406227  0.87605805]
 [-5.          3.         10.         11.5758369   0.52789675  2.60117315]
 [ 0.          0.          0.          0.          0.          0.        ]
 [10.         10.         10.         17.32050808  0.95531662  0.78539816]]


In [10]:
sorted_points_optimized = wp.sort_points_theta_phi_optimized(cartesian_spherical_points, num_cols=num_cols, num_rows=num_rows)
print()
print("Sort function:")
print(sorted_points_optimized)
print("Hand calculated:")
print(res)


Sort function:
[[[16. 18. 16.]
  [-5.  3. 10.]]

 [[ 0.  0.  0.]
  [-1. -2. -3.]]]
Hand calculated:
[[[ 4.   4.5  4. ]
  [-5.   3.  10. ]]

 [[ 0.   0.   0. ]
  [-1.  -2.  -3. ]]]
